accumulate_grad_batches: 1
adam_b1: 0.8
adam_b2: 0.99
amp: false
audio_num_mel_bins: 80
audio_sample_rate: 22050
base_config:
- configs/tts/hifigan.yaml
- configs/tts/libritts/base_mel2wav.yaml
binarization_args:
  shuffle: false
  trim_eos_bos: false
  trim_sil: false
  with_align: false
  with_f0: true
  with_f0cwt: false
  with_linear: false
  with_spk_embed: false
  with_txt: true
  with_wav: true
binarizer_cls: data_gen.tts.base_binarizer.BaseBinarizer
binary_data_dir: data/binary/ljspeech_wav
check_val_every_n_epoch: 10
clip_grad_norm: 1
clip_grad_value: 0
debug: false
dec_ffn_kernel_size: 9
dec_layers: 4
dict_dir: ''
disc_start_steps: 40000
discriminator_grad_norm: 1
discriminator_optimizer_params:
  eps: 1.0e-06
  lr: 0.0002
  weight_decay: 0.0
discriminator_params:
  bias: true
  conv_channels: 64
  in_channels: 1
  kernel_size: 3
  layers: 10
  nonlinear_activation: LeakyReLU
  nonlinear_activation_params:
    negative_slope: 0.2
  out_channels: 1
  use_weight_norm: true
discriminator_scheduler_params:
  gamma: 0.999
  step_size: 600
dropout: 0.1
ds_workers: 1
enc_ffn_kernel_size: 9
enc_layers: 4
endless_ds: true
ffn_act: gelu
ffn_padding: SAME
fft_size: 1024
fm_loss: false
fmax: 8000
fmin: 80
frames_multiple: 1
gen_dir_name: ''
generator_grad_norm: 10
generator_optimizer_params:
  eps: 1.0e-06
  lr: 0.0002
  weight_decay: 0.0
generator_params:
  aux_channels: 80
  aux_context_window: 0
  dropout: 0.0
  gate_channels: 128
  in_channels: 1
  kernel_size: 3
  layers: 30
  out_channels: 1
  residual_channels: 64
  skip_channels: 64
  stacks: 3
  upsample_net: ConvInUpsampleNetwork
  upsample_params:
    upsample_scales:
    - 4
    - 4
    - 4
    - 4
  use_nsf: false
  use_pitch_embed: false
  use_weight_norm: true
generator_scheduler_params:
  gamma: 0.999
  step_size: 600
griffin_lim_iters: 60
hidden_size: 256
hop_size: 256
infer: false
lambda_adv: 4.0
lambda_mel: 45.0
load_ckpt: ''
loud_norm: false
lr: 2.0
max_epochs: 1000
max_eval_sentences: 1
max_eval_tokens: 60000
max_frames: 1548
max_input_tokens: 1550
max_samples: 8192
max_sentences: 24
max_tokens: 30000
max_updates: 3000000
mel_vmax: 1.5
mel_vmin: -6
min_level_db: -100
num_ckpt_keep: 3
num_heads: 2
num_mels: 80
num_sanity_val_steps: 5
num_spk: 1
optimizer_adam_beta1: 0.9
optimizer_adam_beta2: 0.98
out_wav_norm: false
pitch_extractor: parselmouth
pre_align_args:
  allow_no_txt: false
  denoise: false
  forced_align: mfa
  sox_resample: false
  trim_sil: false
  txt_processor: en
  use_tone: true
pre_align_cls: ''
print_nan_grads: false
processed_data_dir: /workspace/dataset/processed/libritts
profile_infer: false
raw_data_dir: /workspace/dataset/libritts
ref_level_db: 20
rerun_gen: true
resblock: '1'
resblock_dilation_sizes:
- - 1
  - 3
  - 5
- - 1
  - 3
  - 5
- - 1
  - 3
  - 5
resblock_kernel_sizes:
- 3
- 7
- 11
reset_phone_dict: true
resume_from_checkpoint: 0
sampling_rate: 22050
save_best: true
save_codes: []
save_f0: false
save_gt: true
seed: 1234
sort_by_len: true
stft_loss_params:
  fft_sizes:
  - 1024
  - 2048
  - 512
  hop_sizes:
  - 120
  - 240
  - 50
  win_lengths:
  - 600
  - 1200
  - 240
  window: hann_window
stop_token_weight: 5.0
task_cls: tasks.vocoder.hifigan.HifiGanTask
tb_log_interval: 100
test_input_dir: ''
test_num: 100
test_set_name: test
train_set_name: train
upsample_initial_channel: 512
upsample_kernel_sizes:
- 16
- 16
- 4
- 4
upsample_rates:
- 8
- 8
- 2
- 2
use_mel_loss: false
use_pitch_embed: false
val_check_interval: 2000
valid_monitor_key: val_loss
valid_monitor_mode: min
valid_set_name: valid
vocoder: pwg
vocoder_ckpt: ''
warmup_updates: 8000
weight_decay: 0
win_length: null
win_size: 1024
window: hann
work_dir: /workspace/checkpoints/hifi
